project_name: htmltest

builds:
  - binary: htmltest
    main: ./main.go
    goos:
      - windows
      - darwin
      - linux
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

changelog:
  sort: asc
  filters:
    exclude:
    - Merge pull request
    - Merge branch

archives:
  - id: default
    replacements:
      darwin: macos
      linux: linux
      windows: windows
      386: i386
      amd64: amd64
      openbsd: openbsd
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: wjdp
    name: htmltest

  draft: true


